### PR TITLE
Add CUDA support to smoothing routine

### PR DESCRIPTION
**Pull request by EtienneBachmann**
Some differences remain between CPU and GPU version :  
 - GPU uses the quadrature rule while it is an option for CPU version.
-  GPU checks the distance criterion between each GLL point and each spectral element while CPU checks distance between each spectral element and each spectral element.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 413](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/413). Fix your mistakes and push your changes back to your branch EtienneBachmann/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 414](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/414).

**Comment by komatits** [comment]
accept

On 12/18/2015 10:33 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 414
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/414>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/679#issuecomment-165902287>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
