### PR TITLE
Main modif for reciprocity and KH integral

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 385](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/385).

**Comment by komatits** [comment]
accept

On 10/01/2015 12:22 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 385
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/385>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/637#issuecomment-144687968>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by EtienneBachmann** [comment]
It seems that this commit broke xmeshfem3D. I tried to run it on the example Meshfem3D_example/simple_model, and it failed.

**Pull request merged**
