### PR TITLE
updates to address compiler issues

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 899](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/899). Please fix the problems and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 900](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/900).

**Comment by danielpeter** [comment]
accept



On 20 Apr 2021, at 12:09 AM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 900<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/900__;!!Nmw4Hv0!mr7mCL3zblXvhNgfzZ699LSApSlutCAoPJZqlLov43k84iPyEsEFzH48GS_-Stajalh-gg$>.

**Pull request merged**
