### PR TITLE
added Vadim Monteiller's new FWI inversion framework for SPECFEM

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 697](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/697). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 698](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/698). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 699](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/699). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 700](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/700). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 701](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/701). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 702](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/702). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 703](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/703). Please fix the problems and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Cannot reproduce the problem, and all the steps compile fine; the unit test then does not compile, probably because a script in the testing system was not updated automatically. Thus accepting the request manually (no other option).

**Pull request merged**
