### PR TITLE
removed the very large and unused save_Q_arrays_*.bin arrays mentioned by Federica Magnoni

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 217](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/217).

**Comment by komatits** [comment]
accept

On 02/04/2015 02:10 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 217
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/217>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/384#issuecomment-72771432>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
I don't understand why the `it_store_attenuation_arrays` subroutine can't just be removed entirely. That is what version control is for after all.

**Comment by komatits** [comment]
done

On 02/04/2015 03:28 AM, Elliott Sales de Andrade wrote:
> I don't understand why the |it_store_attenuation_arrays| subroutine
> can't just be removed entirely. That is what version control is for
> after all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/384#issuecomment-72779148>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
