### PR TITLE
Devel pull request

### PR DESCRIPTION
**Pull request by kbai**
Dear developers,

Two bug fixed. See attached.

Thank you
Kangchen

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 253](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/253). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 254](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/254).

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by kbai** [comment]
I was trying to fix the indentation...

**Comment by komatits** [comment]
reject

On 03/02/2015 02:54 AM, buildbot-princeton wrote:
> You pushed to your local branch while your previous changes are waiting
> to be committed. We assume that you did not intend for these changes to
> be part of the currently opened pull-request and ignore those changes.
> If you want these changes to be committed, please open a new pull-request.
>
> *Note to maintainers:* when you accept the original pull-request, the
> message from buildbot will say that it *closed* the pull-request, as
> opposed to the usual message that it *merged* the pull-request. In spite
> of this, the initial pull-request will be merged after you accept it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/440#issuecomment-76647891>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
reject

On 03/02/2015 02:42 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 254
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/254>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/440#issuecomment-76647226>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi,

There were several error messages related to your pull request and thus 
I closed it. Please open a new one or send me a tar file of your 
modified source code and I will commit it.

Thanks,
Dimitri.

On 03/02/2015 02:32 PM, buildbot-princeton wrote:
> Closed #440 <https://github.com/geodynamics/specfem3d/pull/440>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/440#event-244348228>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
