### PR TITLE
Add comments and rm useless tabs and white spaces, etc

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 290](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/290).

**Comment by bottero** [comment]
accept

**Comment by luet** [comment]
@bottero there is no point in accepting something that you have already
merged on the web site.

On Thu, Apr 9, 2015 at 9:41 AM, Bottero <notifications@github.com> wrote:

> accept
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/479#issuecomment-91235234>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request merged**
