### PR TITLE
Light DSM coupling version : new lists and outputs unmerged + clean meshfem3D

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by durochat** [comment]
It doesn't take into account the unmerged commit "Light DSM coupling version : new lists and outputs". How I can launch a PR with the commit  "Light DSM coupling version : new lists and outputs" from now please ? 

Thanks,
Clément.

**Comment by luet** [comment]
Aren't those changes the ones in the commit eef9d92904 in which case they
are already there.

On Sat, Apr 11, 2015 at 3:15 PM, Clément Durochat <notifications@github.com>
wrote:

> It doesn't take into account the unmerged commit "Light DSM coupling
> version : new lists and outputs". How I can launch a PR with the commit
> "Light DSM coupling version : new lists and outputs" from now please ?
>
> Thanks,
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/483#issuecomment-91908469>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
Look at the files changed on this commit:
https://github.com/geodynamics/specfem3d/pull/483/files
it shows 0 files.
Look at the diff:
https://patch-diff.githubusercontent.com/raw/geodynamics/specfem3d/pull/483.diff
it's empty. Something isn't right. I think it's because the changes you are
trying to push are already there.

On Sat, Apr 11, 2015 at 5:03 PM, David Luet <luet@princeton.edu> wrote:

> Aren't those changes the ones in the commit eef9d92904 in which case they
> are already there.
>
> On Sat, Apr 11, 2015 at 3:15 PM, Clément Durochat <
> notifications@github.com> wrote:
>
>> It doesn't take into account the unmerged commit "Light DSM coupling
>> version : new lists and outputs". How I can launch a PR with the commit
>> "Light DSM coupling version : new lists and outputs" from now please ?
>>
>> Thanks,
>> Clément.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/483#issuecomment-91908469>
>> .
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by QuLogic** [comment]
@luet is correct. @durochat the commit you want to add is already part of the repo here. You can check using `git log`:

```
$ git fetch upstream
$ git fetch durochat  # This is what I named your fork
$ git log --all --decorate --graph
*   commit a86381cccf60ab35ce6f64e9df5b5433dcff278a (durochat/devel)
|\  Merge: 9bbdafd 231ab49
| | Author: Clément Durochat <c.durochat@gmail.com>
| | Date:   Sat Apr 11 21:01:16 2015 +0200
| | 
| |     Merge branch 'devel' of https://github.com/geodynamics/specfem3d into devel
| |   
| * commit 231ab4966c59b59b9e5396b50c07bea691f99de0 (upstream/devel)
| | Author: buildbot <buildbot@seismobot.Princeton.EDU>
| | Date:   Fri Apr 10 12:00:21 2015 -0400
| | 
| |     Buildbot ran the code beautifier.
| |   
* | commit 9bbdafd15fcee74e2ecd42aae2c7a52c2cc05727
|/  Author: Clément Durochat <c.durochat@gmail.com>
|   Date:   Fri Apr 10 18:14:55 2015 +0200
|   
|       Cleaning meshfem3d
|  
* commit eef9d9290438cd909d0dc4e30ae981ce398964ea
| Author: Clément Durochat <c.durochat@gmail.com>
| Date:   Fri Apr 10 17:57:45 2015 +0200
| 
|      Light DSM coupling version : new lists and outputs
|    
*   commit 3512fff33cd6a945a2c83948d48cf04113396eea (HEAD, origin/devel, devel)
|\  Merge: 7419588 1f5ebb8
| | Author: Bottero <alexis.bottero@gmail.com>
| | Date:   Thu Apr 9 15:40:46 2015 +0200
| | 
| |     Merge pull request #479 from durochat/devel
| |     
| |     accept
| |   
| * commit 1f5ebb840cdf626eaa90447fe5f1dfe618df69f1
```

Unfortunately, I cannot copy all the fancy colours here, but I think it should be clear enough. `upstream/devel` is the geodynamics repo.`durochat/devel` is yours. This PR is a merge between the cleaned up commit you made (9bbdafd15fcee74e2ecd42aae2c7a52c2cc05727) and the cleaned-by-buildbot commit (231ab4966c59b59b9e5396b50c07bea691f99de0). Since your commit is essentially the same as Buildbot's, I think you should just close this PR and reset your copy to match here.

**Comment by durochat** [comment]
Hi all,

Thank you very much for your help. Yes you're right, I verified on github.com/geodynamics/specfem3d/blob/devel/src/meshfem3D/, and it is ok, all the changes are already committed. 

I was confused because I've seen a message, just below the "accept" of Dimitri, who said "the PR is closed without merge this commit" (something like that). But I don't see this notification anymore.

Anyway, everything is ok now and I close this now useless PR.

Thanks again. Best regards,
Clément.

**Pull request closed without merging**
