### PR TITLE
Add seismogram output function in gpu fault solver.

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 474](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/474). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 475](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/475).

**Comment by komatits** [comment]
accept

On 29/04/2016 19:26, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 475
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/475>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/753#issuecomment-215822584>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
