### PR TITLE
ran the new cleaning routine (many changes, but once and for all)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
It seems BuildBot missed it, thus accepting it manually.

**Comment by QuLogic** [comment]
Probably it was too large:
```
 879 files changed, 11008 insertions(+), 12016 deletions(-)
```

@luet ?

**Comment by luet** [comment]
I don't think that's the problem. We had a problem with size before but
this should be fixed now.
I think the problem comes from some non-ASCII characters that were in:
src/decompose_mesh/scotch_5.1.12b/doc:
   - CeCILL-C_V1-fr.txt
   - CeCILL-C_V1-en.txt

If you check out the commit 9581b18b5 , and try to open these files with
vi, you'll only see a small part of the files. But this has been fixed by
Dimitri's commit f86b682.

I don't know what these characters are and I don't know why my test on
non-ASCII characters didn't catch them. But I figured it's probably not
worth spending a lot of time on them.


On Wed, Feb 11, 2015 at 3:00 PM, Elliott Sales de Andrade <
notifications@github.com> wrote:

> Probably it was too large:
>
>  879 files changed, 11008 insertions(+), 12016 deletions(-)
>
> @luet <https://github.com/luet> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73953190>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Hi David and Elliott,

The problem with these two files came from ISO-8859-1 encoding instead 
of UTF-8, and in utils/clean_listings_specfem.pl we assume UTF-8 is used:

iconv -f utf-8 -t ASCII//TRANSLIT


If changing -f utf-8 to -f ISO-8859-1 the script then works for these 
two files (I tried) but not for the others. I am not sure if it can be 
made to work for both

(doing iconv -f utf-8 first and then iconv -f ISO-8859-1 does not work 
because the two files are destroyed by the first iconv, at the first 
accented letter they contain...)

Is there any automatic way of detecting what encoding a given ASCII file 
uses?

Thanks,
Dimitri.

On 02/11/2015 09:29 PM, David Luet wrote:
> I don't think that's the problem. We had a problem with size before but
> this should be fixed now.
> I think the problem comes from some non-ASCII characters that were in:
> src/decompose_mesh/scotch_5.1.12b/doc:
> - CeCILL-C_V1-fr.txt
> - CeCILL-C_V1-en.txt
>
> If you check out the commit 9581b18b5 , and try to open these files with
> vi, you'll only see a small part of the files. But this has been fixed by
> Dimitri's commit f86b682.
>
> I don't know what these characters are and I don't know why my test on
> non-ASCII characters didn't catch them. But I figured it's probably not
> worth spending a lot of time on them.
>
>
> On Wed, Feb 11, 2015 at 3:00 PM, Elliott Sales de Andrade <
> notifications@github.com> wrote:
>
>  > Probably it was too large:
>  >
>  > 879 files changed, 11008 insertions(+), 12016 deletions(-)
>  >
>  > @luet <https://github.com/luet> ?
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73953190>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73958349>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
by "ASCII file" below I mean "text file" ;-)

On 02/11/2015 11:06 PM, Dimitri Komatitsch wrote:
> Hi David and Elliott,
>
> The problem with these two files came from ISO-8859-1 encoding instead
> of UTF-8, and in utils/clean_listings_specfem.pl we assume UTF-8 is used:
>
> iconv -f utf-8 -t ASCII//TRANSLIT
>
>
> If changing -f utf-8 to -f ISO-8859-1 the script then works for these
> two files (I tried) but not for the others. I am not sure if it can be
> made to work for both
>
> (doing iconv -f utf-8 first and then iconv -f ISO-8859-1 does not work
> because the two files are destroyed by the first iconv, at the first
> accented letter they contain...)
>
> Is there any automatic way of detecting what encoding a given ASCII file
> uses?
>
> Thanks,
> Dimitri.
>
> On 02/11/2015 09:29 PM, David Luet wrote:
>> I don't think that's the problem. We had a problem with size before but
>> this should be fixed now.
>> I think the problem comes from some non-ASCII characters that were in:
>> src/decompose_mesh/scotch_5.1.12b/doc:
>> - CeCILL-C_V1-fr.txt
>> - CeCILL-C_V1-en.txt
>>
>> If you check out the commit 9581b18b5 , and try to open these files with
>> vi, you'll only see a small part of the files. But this has been fixed by
>> Dimitri's commit f86b682.
>>
>> I don't know what these characters are and I don't know why my test on
>> non-ASCII characters didn't catch them. But I figured it's probably not
>> worth spending a lot of time on them.
>>
>>
>> On Wed, Feb 11, 2015 at 3:00 PM, Elliott Sales de Andrade <
>> notifications@github.com> wrote:
>>
>>  > Probably it was too large:
>>  >
>>  > 879 files changed, 11008 insertions(+), 12016 deletions(-)
>>  >
>>  > @luet <https://github.com/luet> ?
>>  >
>>  > —
>>  > Reply to this email directly or view it on GitHub
>>  >
>> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73953190>.
>>
>>  >
>>
>>
>>
>> --
>> David Luet
>> Linux Administrator/Software & Programming Analyst
>> Department of Geosciences & PICSciE
>> Princeton University
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73958349>.
>>
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
> Is there any automatic way of detecting what encoding a given text file uses?

No, not sanely, anyway. Best to just mandate UTF-8 or plain 7-bit ASCII and reject anything else.

**Comment by komatits** [comment]
Thanks!
I agree, let us reject the rest.

On 02/11/2015 11:22 PM, Elliott Sales de Andrade wrote:
>     Is there any automatic way of detecting what encoding a given text
>     file uses?
>
> No, not sanely, anyway. Best to just mandate UTF-8 or plain 7-bit ASCII
> and reject anything else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/400#issuecomment-73977819>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
