### PR TITLE
Light DSM coupling version : spherical coordinate on all chunk surface GLL, v2

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 287](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/287). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
The errors come from unused variables:
    src/meshfem3D/earth_chunk_all_Utils.f90:154.80:
    
    routine cartesian_product_to_r_theta_phi_on_chunk_surface_GLL(MESH, deg2rad)
                                                                           1     
    Warning: Unused dummy argument 'deg2rad' at (1)
    src/meshfem3D/earth_chunk_all_Utils.f90:164.100:
    
    ax_val1, ymax_val2, zmin_val1, zmin_val2, zmin_fix, x, y ,z, R, R_m, latrad, lg
                                                                           1                         
    Warning: Unused variable 'latrad' declared at (1)
    src/meshfem3D/earth_chunk_all_Utils.f90:164.107:

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by durochat** [comment]
Yes, I didn't know it generated errors on buildbot, as there was no error (just warning) when I compiled it on cluster Curie.

I corrected, and did commit + push

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 288](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/288). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by durochat** [comment]
Definitely...

There is an error for compile_intel, but I never touched any file about this... I don't how to fix that ! 

make -j 8 --always-make
/home/buildbot/scripts/specfem3d/compile_intel.sh: line 23: ============================: command not found
ifort -g -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03 -diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -DFORCE_VECTORIZATION  -mod ./obj -I./obj -I.  -I./setup  -c -o obj/shared_par.shared_module.o src/shared/shared_par.f90
icc -c -I./setup  -I/usr/include/scotch -DFORCE_VECTORIZATION -DWITH_MPI -g -O2 -I./setup  -I/usr/include/scotch -DFORCE_VECTORIZATION -DWITH_MPI -o obj/param_reader.cc.o src/shared/param_reader.c
Using bundled Scotch in directory: ./src/decompose_mesh/scotch/src
make -C ./src/decompose_mesh/scotch/src
ifort -g -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03 -diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -DFORCE_VECTORIZATION  -mod ./obj -I./obj -I.  -I./setup  -c -o obj/adios_manager_stubs.shared_noadios.o src/shared/adios_manager_stubs.f90
make[1]: Entering directory `/home/buildbot/slaves/specfem3d/specfem3d_builder/build/src/decompose_mesh/scotch_5.1.12b/src'
mkdir ../bin
mkdir ../include
mkdir ../lib
mkdir: cannot create directory `../lib': File exists
make[1]: [../lib] Error 1 (ignored)
mkdir: cannot create directory `../bin': File exists
make[1]: [../bin] Error 1 (ignored)
mkdir: cannot create directory `../include': File exists
make[1]: [../include] Error 1 (ignored)

**Comment by durochat** [comment]
Apparently it's a problem specifice to intel : 

src/generate_databases/create_regions_mesh.f90(199): internal error: Please visit 'http://www.intel.com/software/products/support' for assistance.
  call get_model(myrank)
^
[ Aborting due to internal error. ]
compilation aborted for src/generate_databases/create_regions_mesh.f90 (code 1)
make: *** [obj/create_regions_mesh.gen.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by luet** [comment]
It passed the buildbot test: [build 289](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/289).
I am not sure what happened before. It ran again without changes.
I merged it and closed the PR.

**Comment by durochat** [comment]
Thanks, yes really weird error about compile_intel, I never seen this before...
Thank you for your help. Best,
Clément

**Comment by komatits** [comment]
Hi all,

Very unlikely. The problem must be elsewhere
(I do not see how that compiler could have a problem calling a subroutine).

Best wishes,
Dimitri.

On 04/08/2015 06:17 PM, Clément Durochat wrote:
> Apparently it's a problem specifice to intel :
>
> src/generate_databases/create_regions_mesh.f90(199): internal error:
> Please visit 'http://www.intel.com/software/products/support' for
> assistance.
> call get_model(myrank)
> ^
> [ Aborting due to internal error. ]
> compilation aborted for src/generate_databases/create_regions_mesh.f90
> (code 1)
> make: *** [obj/create_regions_mesh.gen.o] Error 1
> make: *** Waiting for unfinished jobs....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/478#issuecomment-90963795>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
Hi all, 

Yes and the problem seems to have been solved itself... The day after I did another pull-request (with no change in create_regions_mesh ou get_model) and there was no problem...

Cheers,
Clément.

**Comment by komatits** [comment]
Hi all,

If you analyze the error messages below you can see that there is an 
error at line 23 of /home/buildbot/scripts/specfem3d/compile_intel.sh
(a comment that does not start with a # sign)
and another error:

mkdir ../lib
mkdir: cannot create directory|../lib': File exists


(use "mkdir -p" instead of "mkdir" to fix that)

Dimitri.

On 04/08/2015 06:10 PM, Clément Durochat wrote:
> Definitely...
>
> There is an error for compile_intel, but I never touched any file about
> this... I don't how to fix that !
>
> make -j 8 --always-make
> /home/buildbot/scripts/specfem3d/compile_intel.sh: line 23:
> ============================: command not found
> ifort -g -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align
> sequence -vec-report0 -std03 -diag-disable 6477 -implicitnone
> -gen-interfaces -warn all -O3 -check nobounds -DFORCE_VECTORIZATION -mod
> ./obj -I./obj -I. -I./setup -c -o obj/shared_par.shared_module.o
> src/shared/shared_par.f90
> icc -c -I./setup -I/usr/include/scotch -DFORCE_VECTORIZATION -DWITH_MPI
> -g -O2 -I./setup -I/usr/include/scotch -DFORCE_VECTORIZATION -DWITH_MPI
> -o obj/param_reader.cc.o src/shared/param_reader.c
> Using bundled Scotch in directory: ./src/decompose_mesh/scotch/src
> make -C ./src/decompose_mesh/scotch/src
> ifort -g -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align
> sequence -vec-report0 -std03 -diag-disable 6477 -implicitnone
> -gen-interfaces -warn all -O3 -check nobounds -DFORCE_VECTORIZATION -mod
> ./obj -I./obj -I. -I./setup -c -o
> obj/adios_manager_stubs.shared_noadios.o src/shared/adios_manager_stubs.f90
> make[1]: Entering directory
> |/home/buildbot/slaves/specfem3d/specfem3d_builder/build/src/decompose_mesh/scotch_5.1.12b/src'
> mkdir ../bin
> mkdir ../include
> mkdir ../lib
> mkdir: cannot create directory|../lib': File exists
> make[1]: [../lib] Error 1 (ignored)
> mkdir: cannot create directory |../bin': File exists
> make[1]: [../bin] Error 1 (ignored)
> mkdir: cannot create directory|../include': File exists
> make[1]: [../include] Error 1 (ignored)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/478#issuecomment-90961945>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
