### PR TITLE
Light DSM coupling version : spherical coordinate on all chunk surface GLL

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 281](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/281). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by durochat** [comment]
I push the corrections, as usual, but the pull-request didn't reopen ? How I can reopen and finish this pull-request ?

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 283](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/283). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
This problem in on my side. Let me fix it.

On Wed, Apr 8, 2015 at 10:32 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 283
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/283>.
> Fix your mistakes and push your changes back to your branch
> durochat/specfem3d:devel. This pull-request will be reopened automatically.
> You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/476#issuecomment-90934018>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
It looks like there are still some issues with unused variables. See build
286
<http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/286>
.
I am just going to close that pull-request. Things got messy. Please open a
new pull-request.

On Wed, Apr 8, 2015 at 10:34 AM, David Luet <luet@princeton.edu> wrote:

> This problem in on my side. Let me fix it.
>
> On Wed, Apr 8, 2015 at 10:32 AM, buildbot-princeton <
> notifications@github.com> wrote:
>
>> Your changes failed the buildbot test. See build 283
>> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/283>.
>> Fix your mistakes and push your changes back to your branch
>> durochat/specfem3d:devel. This pull-request will be reopened automatically.
>> You don't need to create a new pull request
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/476#issuecomment-90934018>
>> .
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by durochat** [comment]
Ok perfect, thank you !

**Pull request closed without merging**
