### PR TITLE
moved 8 useful parameters from setup/constants.h.in to DATA/Par_file

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 226](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/226). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 227](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/227).

**Comment by komatits** [comment]
accept

On 02/12/2015 03:29 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 227
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/227>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/407#issuecomment-74006979>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
