### PR TITLE
added CPML support for the internal mesher (by Chang-hua Zhang)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 345](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/345). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 346](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/346). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 347](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/347). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 348](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/348).

**Comment by komatits** [comment]
accept

On 06/20/2015 01:08 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 348
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/348>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/571#issuecomment-113667961>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by specfem3d-zhang-ksu** [comment]
Nice.

**Pull request merged**
