### PR TITLE
Internal Mesher and External Source Time Function examples for the default Homogeneous Halfspace example

### PR DESCRIPTION
**Pull request by aakash10gupta**
These examples run the same simulation as the default homogeneous halfspace example. While the default example is based on an external mesher and the inbuilt source time function, these examples will help the user use the internal mesher as well as an externally provided source time function to run the same simulation.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by carltape** [comment]
Thanks, Aakash. Daniel, we're hoping to demonstrate the basics of the internal meshing at the upcoming user's workshop, so this is the main reason for the update here.

**Comment by Geotomo** [comment]
Dear Carl Tape
Will the workshop be recorded, or is there an online option?
-An user outside US



在 2022-08-30 14:11:01，"Carl Tape" ***@***.***> 写道：

Thanks, Aakash. Daniel, we're hoping to demonstrate the basics of the internal meshing at the upcoming user's workshop, so this is the main reason for the update here.

**Comment by danielpeter** [comment]
accept


On 30 Aug 2022, at 5:29 AM, buildbot-princeton ***@***.******@***.***>> wrote:



The files changed do not require a buildbot test. The maintainers can commit these changes.

**Pull request merged**
