### PR TITLE
fixed the unit tests in the "tests" directory; changed directory paths to the same name as in SPECFEM3D_GLOBE to make the two packages more similar; removed an unused routine and the corresponding file (src/shared/create_serial_name_database.f90)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 232](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/232). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 233](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/233).

**Comment by komatits** [comment]
accept

On 02/15/2015 10:33 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 233
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/233>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/413#issuecomment-74438268>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
