### PR TITLE
LDDRK implementation for forward run with noDev version

### PR DESCRIPTION
**Pull request by xiezhinan**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 313](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313).

**Comment by komatits** [comment]
accept

On 05/27/2015 03:12 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 313
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/519#issuecomment-105901699>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by danielpeter** [comment]
Hi Zhinan, 

could you check and possibly fix the remarks about unused variables introduced by your commits? 

search for 'remark' to see the corresponding files in this intel-compiler log:
http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313/steps/compile_intel/logs/stdio

many thanks,
daniel

**Comment by komatits** [comment]
Hi Zhinan, Daniel and David,

Fixed!

David, could you make BuildBot see unused variables as an error instead 
of a warning and reject all pull requests with unused variables? I do 
not have time to fix them manually myself anymore, and we get a lot of 
these.

Zhinan, here are the two things that I removed because they were unused, 
could you check? (it seems weird that the subroutine for instance was 
totally unused):

- subroutine compute_element_att_memory_lddrk() was not used at all 
(never called from anywhere) thus I removed it

- in compute_forces_viscoelastic_noDev() the following variables were 
unused and thus I removed them: 
R_trace_lddrk,R_xx_lddrk,R_yy_lddrk,R_xy_lddrk,R_xz_lddrk,R_yz_lddrk

Thanks,
Dimitri.

On 06/03/2015 08:13 AM, daniel peter wrote:
> Hi Zhinan,
>
> could you check and possibly fix the remarks about unused variables
> introduced by your commits?
>
> search for 'remark' to see the corresponding files in this
> intel-compiler log:
> http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313/steps/compile_intel/logs/stdio
>
> many thanks,
> daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/519#issuecomment-108205666>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
David, could you make BuildBot see unused variables as an error instead of
> a warning and reject all pull requests with unused variables? I do not have
> time to fix them manually myself anymore, and we get a lot of these.
>

My guess is that it's something that needs to changed in the configure file
so that it appears in the Makefile. I thought that was the way it was set
up for GNU compilers. I am surprised GNU didn't catch them.
Best,
David

> Zhinan, here are the two things that I removed because they were unused,
> could you check? (it seems weird that the subroutine for instance was
> totally unused):
>
> - subroutine compute_element_att_memory_lddrk() was not used at all (never
> called from anywhere) thus I removed it
>
> - in compute_forces_viscoelastic_noDev() the following variables were
> unused and thus I removed them:
> R_trace_lddrk,R_xx_lddrk,R_yy_lddrk,R_xy_lddrk,R_xz_lddrk,R_yz_lddrk
>
> Thanks,
> Dimitri.
>
>
> On 06/03/2015 08:13 AM, daniel peter wrote:
>
>> Hi Zhinan,
>>
>> could you check and possibly fix the remarks about unused variables
>> introduced by your commits?
>>
>> search for 'remark' to see the corresponding files in this
>> intel-compiler log:
>>
>> http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313/steps/compile_intel/logs/stdio
>>
>> many thanks,
>> daniel
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/519#issuecomment-108205666
>> >.
>>
>>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France    http://komatitsch.free.fr
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Hi David,

It does appear in the configure file (more precisely in flags.guess) for 
GNU gfortran:

-Wunused -Werror

(-Werror converts warnings to errors)

Dimitri.

On 06/03/2015 07:04 PM, David Luet wrote:
>
>
>     David, could you make BuildBot see unused variables as an error
>     instead of a warning and reject all pull requests with unused
>     variables? I do not have time to fix them manually myself anymore,
>     and we get a lot of these.
>
>
> My guess is that it's something that needs to changed in the configure
> file so that it appears in the Makefile. I thought that was the way it
> was set up for GNU compilers. I am surprised GNU didn't catch them.
> Best,
> David
>
>     Zhinan, here are the two things that I removed because they were
>     unused, could you check? (it seems weird that the subroutine for
>     instance was totally unused):
>
>     - subroutine compute_element_att_memory_lddrk() was not used at all
>     (never called from anywhere) thus I removed it
>
>     - in compute_forces_viscoelastic_noDev() the following variables
>     were unused and thus I removed them:
>     R_trace_lddrk,R_xx_lddrk,R_yy_lddrk,R_xy_lddrk,R_xz_lddrk,R_yz_lddrk
>
>     Thanks,
>     Dimitri.
>
>
>     On 06/03/2015 08:13 AM, daniel peter wrote:
>
>         Hi Zhinan,
>
>         could you check and possibly fix the remarks about unused variables
>         introduced by your commits?
>
>         search for 'remark' to see the corresponding files in this
>         intel-compiler log:
>         http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313/steps/compile_intel/logs/stdio
>
>         many thanks,
>         daniel
>
>         —
>         Reply to this email directly or view it on GitHub
>         <https://github.com/geodynamics/specfem3d/pull/519#issuecomment-108205666>.
>
>
>     --
>     Dimitri Komatitsch
>     CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>     UPR 7051, Marseille, France http://komatitsch.free.fr
>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Dear Daniel, David and Dimitri,

I have fixed the bug in viscoelastic simulation with LDDRK.
Some part of the code did not committed, which results some unused variables.
Now it is fine.

Thank you so much.
Best regards,
Zhinan







At 2015-06-04 01:04:08, "David Luet" <luet@princeton.edu> wrote:





David, could you make BuildBot see unused variables as an error instead of a warning and reject all pull requests with unused variables? I do not have time to fix them manually myself anymore, and we get a lot of these.



My guess is that it's something that needs to changed in the configure file so that it appears in the Makefile. I thought that was the way it was set up for GNU compilers. I am surprised GNU didn't catch them.
Best,
David 

Zhinan, here are the two things that I removed because they were unused, could you check? (it seems weird that the subroutine for instance was totally unused):

- subroutine compute_element_att_memory_lddrk() was not used at all (never called from anywhere) thus I removed it

- in compute_forces_viscoelastic_noDev() the following variables were unused and thus I removed them: R_trace_lddrk,R_xx_lddrk,R_yy_lddrk,R_xy_lddrk,R_xz_lddrk,R_yz_lddrk

Thanks,
Dimitri.


On 06/03/2015 08:13 AM, daniel peter wrote:

Hi Zhinan,

could you check and possibly fix the remarks about unused variables
introduced by your commits?

search for 'remark' to see the corresponding files in this
intel-compiler log:
http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/313/steps/compile_intel/logs/stdio

many thanks,
daniel

—
Reply to this email directly or view it on GitHub

<https://github.com/geodynamics/specfem3d/pull/519#issuecomment-108205666>.



--
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr






--

David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request merged**
