### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 363](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/363). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 364](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/364).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
