### PR TITLE
Light DSM coupling version : new lists and outputs

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 291](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/291).

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by komatits** [comment]
accept

On 04/10/2015 06:05 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 291
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/291>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/480#issuecomment-91602557>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
The buildbot didn't merge this PR, because I did a tiny git push (just for clean things) before this PR was accept. I launch another PR with all the changes.

**Comment by luet** [comment]
I don't think this is correct. This commit: eef9d9 has been merged properly
on April 10.
Then buildbot ran the code beautifier, and created another commit: 231ab4.

On Sat, Apr 11, 2015 at 2:52 PM, Clément Durochat <notifications@github.com>
wrote:

> The buildbot didn't merge this PR, because I did a tiny git push (just for
> clean things) before this PR was accept. I launch another PR with all the
> changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/480#issuecomment-91901525>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
