### PR TITLE
updates two CPML examples (adding reference seismograms for checking) 

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 495](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/495).

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by komatits** [comment]
accept

On 10/07/2016 23:48, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 495
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/495>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/779#issuecomment-231612865>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKeT5mJw6kf8__iDyLK8V32N9Jvscks5qUWiwgaJpZM4JI7Jd>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
