### PR TITLE
add support of non-flat fluid-solid interface in PML:

### PR DESCRIPTION
**Pull request by xiezhinan**
fix the computation of force acting upon solid

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 615](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/615). Fix your mistakes and push your changes back to your branch xiezhinan/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
I tried compiling with Intel and it worked this time. So maybe we can just accept it.

**Comment by xiezhinan** [comment]
Hi David,

Thank you so much.
I committed again the change.
Since I do not know how to fix the problem that:
my branch is one commit ahead.

Thus I use one stupid way to solve that, i.e., to refork the specfem3d.
Then I retype my change and commit them

Thank you so much,
Best regards,
Zhinan

**Pull request closed without merging**
