### PR TITLE
bug fixes for adjoint simulations; faster source location

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 309](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/309).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
Added faster receiver location detection (got rid of sqrt() in distance 
comparisons).

Dimitri.

On 05/20/2015 02:21 PM, daniel peter wrote:
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/geodynamics/specfem3d/pull/511
>
>
>         Commit Summary
>
>   * bug fix for source orientation
>   * bug fix for seismogram outputs of adjoint receivers in pure adjoint
>     simulations
>   * adds distance criterion for faster source location detection
>
>
>         File Changes
>
>   * *M* setup/constants.h.in
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-0> (56)
>   * *M* src/shared/get_cmt.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-1> (3)
>   * *M* src/shared/get_force.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-2> (3)
>   * *M* src/shared/parallel.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-3> (3)
>   * *M* src/shared/read_parameter_file.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-4> (9)
>   * *M* src/shared/read_topo_bathy_file.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-5> (22)
>   * *M* src/shared/read_value_parameters.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-6> (3)
>   * *M* src/specfem3D/compute_interpolated_dva.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-7> (55)
>   * *M* src/specfem3D/locate_source.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-8> (189)
>   * *M* src/specfem3D/prepare_timerun.F90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-9> (6)
>   * *M* src/specfem3D/setup_sources_receivers.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-10> (169)
>   * *M* src/specfem3D/write_output_ASCII_or_binary.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-11> (4)
>   * *M* src/specfem3D/write_seismograms.f90
>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-12> (316)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem3d/pull/511.patch
>   * https://github.com/geodynamics/specfem3d/pull/511.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/511>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Also done for source location detection (can be useful when using many 
sources, e.g. for large earthquakes).

Dimitri.

On 05/21/2015 06:50 PM, Dimitri Komatitsch wrote:
>
> Added faster receiver location detection (got rid of sqrt() in distance
> comparisons).
>
> Dimitri.
>
> On 05/20/2015 02:21 PM, daniel peter wrote:
>> ------------------------------------------------------------------------
>>
>>
>>         You can view, comment on, or merge this pull request online at:
>>
>> https://github.com/geodynamics/specfem3d/pull/511
>>
>>
>>         Commit Summary
>>
>>   * bug fix for source orientation
>>   * bug fix for seismogram outputs of adjoint receivers in pure adjoint
>>     simulations
>>   * adds distance criterion for faster source location detection
>>
>>
>>         File Changes
>>
>>   * *M* setup/constants.h.in
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-0> (56)
>>   * *M* src/shared/get_cmt.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-1> (3)
>>   * *M* src/shared/get_force.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-2> (3)
>>   * *M* src/shared/parallel.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-3> (3)
>>   * *M* src/shared/read_parameter_file.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-4> (9)
>>   * *M* src/shared/read_topo_bathy_file.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-5> (22)
>>   * *M* src/shared/read_value_parameters.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-6> (3)
>>   * *M* src/specfem3D/compute_interpolated_dva.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-7> (55)
>>   * *M* src/specfem3D/locate_source.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-8>
>> (189)
>>   * *M* src/specfem3D/prepare_timerun.F90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-9> (6)
>>   * *M* src/specfem3D/setup_sources_receivers.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-10>
>> (169)
>>   * *M* src/specfem3D/write_output_ASCII_or_binary.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-11> (4)
>>   * *M* src/specfem3D/write_seismograms.f90
>>     <https://github.com/geodynamics/specfem3d/pull/511/files#diff-12>
>> (316)
>>
>>
>>         Patch Links:
>>
>>   * https://github.com/geodynamics/specfem3d/pull/511.patch
>>   * https://github.com/geodynamics/specfem3d/pull/511.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/511>.
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
