### PR TITLE
Fix a bug in shapeval initiation in dynamic fault solver

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 282](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/282).

**Comment by komatits** [comment]
accept

On 04/07/2015 11:21 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 282
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/282>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/477#issuecomment-90736165>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
@kbai You need to wait for @buildbot-princeton and not merge yourself.

**Comment by kbai** [comment]
Sorry, my mistake. I waited for sometime and thought that the robot was not
going to start.


Kangchen

**Comment by luet** [comment]
Do you have special permissions on CIG's GitHub? Normally users without
administrative rights cannot merge their own pull-requests.

On Tue, Apr 7, 2015 at 7:29 PM, Kangchen Bai <notifications@github.com>
wrote:

> Sorry, my mistake. I waited for sometime and thought that the robot was not
> going to start.
>
>
> Kangchen
>
> On Tue, Apr 7, 2015 at 4:24 PM, Elliott Sales de Andrade <
> notifications@github.com> wrote:
>
> > @kbai <https://github.com/kbai> You need to wait for @buildbot-princeton
> > <https://github.com/buildbot-princeton> and not merge yourself.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/geodynamics/specfem3d/pull/477#issuecomment-90758708
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/477#issuecomment-90759590>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by kbai** [comment]
Yes,  the developer team was expanded sometime last month.

**Pull request merged**
