### PR TITLE
Fix the remaining hardcoded par_file path in faultsolver

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 271](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/271). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 272](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/272).

**Comment by komatits** [comment]
accept

On 03/16/2015 05:04 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 272
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/272>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/459#issuecomment-81762974>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
Sorry I didn't notice that earlier. The problem was on our side.
We had a campus wide network problem last night and buildbot wasn't able to contact GitHub.
I just reran the test by hand.

**Comment by komatits** [comment]
It seems these changes do not get merged for some reason, even though 
they pass the BuildBot test and I then accept them. Not sure why.

On 03/16/2015 05:05 PM, buildbot-princeton wrote:
> Closed #459 <https://github.com/geodynamics/specfem3d/pull/459>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/459#event-255706542>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKQtTwR2JcQy-46mEwZo0rDN-qMZJks5n1va5gaJpZM4DvCHr.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
Ok. Let me take care of merging them.

On Mon, Mar 16, 2015 at 12:06 PM, Dimitri Komatitsch <
notifications@github.com> wrote:

> It seems these changes do not get merged for some reason, even though
> they pass the BuildBot test and I then accept them. Not sure why.
>
> On 03/16/2015 05:05 PM, buildbot-princeton wrote:
> > Closed #459 <https://github.com/geodynamics/specfem3d/pull/459>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/geodynamics/specfem3d/pull/459#event-255706542>.Web
> > Bug from
> >
> https://github.com/notifications/beacon/AFjDKQtTwR2JcQy-46mEwZo0rDN-qMZJks5n1va5gaJpZM4DvCHr.gif
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/459#issuecomment-81764178>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Thanks!

Dimitri.

On 03/16/2015 05:08 PM, David Luet wrote:
> Ok. Let me take care of merging them.
>
> On Mon, Mar 16, 2015 at 12:06 PM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  > It seems these changes do not get merged for some reason, even though
>  > they pass the BuildBot test and I then accept them. Not sure why.
>  >
>  > On 03/16/2015 05:05 PM, buildbot-princeton wrote:
>  > > Closed #459 <https://github.com/geodynamics/specfem3d/pull/459>.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <https://github.com/geodynamics/specfem3d/pull/459#event-255706542>.Web
>  > > Bug from
>  > >
>  >
> https://github.com/notifications/beacon/AFjDKQtTwR2JcQy-46mEwZo0rDN-qMZJks5n1va5gaJpZM4DvCHr.gif
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/459#issuecomment-81764178>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/459#issuecomment-81764745>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 273](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/273).

**Comment by luet** [comment]
Done.

**Comment by kbai** [comment]
Thanks for your help.

**Pull request closed without merging**
