### PR TITLE
Add heterogeneous frictional properties input in fault solver.

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 371](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/371). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 372](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/372).

**Comment by kbai** [comment]
I close it because I forgot an important modification. I will open another later.

**Comment by komatits** [comment]
accept

On 09/04/2015 08:00 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 372
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/372>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/613#issuecomment-137806768>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
