### PR TITLE
For propagation in chunk without coupling

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by durochat** [comment]
@luet @komatits @QuLogic 

Hi all,
Do you know why the buildbot doesn't start ?
Thanks,
Clément.

**Comment by luet** [comment]
Hi Clément,
Sorry I didn't let you know. The machine running buildbot was down for
maintenance last night. It's now running again. But I'll need to trigger it
manually. I may need a couple hours to do it because I have some meetings
this morning. I might be able to multitask during the meetings.
Once I am done you'll see it because it will send the notifications once it
runs the tests.
Best,
David


On Wed, Jan 27, 2016 at 9:21 AM, Clément Durochat <notifications@github.com>
wrote:

> @luet <https://github.com/luet> @komatits <https://github.com/komatits>
> @QuLogic <https://github.com/QuLogic>
>
> Hi all,
> Do you know why the buildbot doesn't start ?
> Thanks,
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/687#issuecomment-175653710>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by durochat** [comment]
Hi David, 
Ok thank your very much ! 
Perfect,
Clément.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 418](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/418). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 419](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/419).

**Comment by komatits** [comment]
accept

On 01/27/2016 05:12 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 419
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/419>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/687#issuecomment-175717042>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
