### PR TITLE
update user manual files and renames noise strength kernel to be consistent with others

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 301](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/301). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
We keep getting this error randomly

    src/specfem3D/compute_forces_viscoelastic_calling_routine.F90(79): internal error: Please visit  
    'http://www.intel.com/software/products/support' for assistance.
      call compute_forces_viscoelastic_noDev(iphase,NSPEC_AB,NGLOB_AB, &
    ^
    [ Aborting due to internal error. ]
    compilation aborted for src/specfem3D/compute_forces_viscoelastic_calling_routine.F90 (code 1)
    make: *** [obj/compute_forces_viscoelastic_calling_routine.spec.o] Error 1
    make: *** Waiting for unfinished jobs....

We have been ignoring it so I think it's safe to merge this commit.

**Comment by luet** [comment]
accept

On Fri, Apr 24, 2015 at 9:17 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 301
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/301>.
> Fix your mistakes and push your changes back to your branch
> danielpeter/specfem3d:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/501#issuecomment-95930445>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
This hasn't worked. Let me merge it by hand now.

**Comment by komatits** [comment]
Yes, probably the Intel compiler having an internal problem.

On 04/24/2015 03:21 PM, David Luet wrote:
> We keep getting this error randomly
>
> |src/specfem3D/compute_forces_viscoelastic_calling_routine.F90(79): internal error: Please visit
> 'http://www.intel.com/software/products/support' for assistance.
>    call compute_forces_viscoelastic_noDev(iphase,NSPEC_AB,NGLOB_AB, &
> ^
> [ Aborting due to internal error. ]
> compilation aborted for src/specfem3D/compute_forces_viscoelastic_calling_routine.F90 (code 1)
> make: *** [obj/compute_forces_viscoelastic_calling_routine.spec.o] Error 1
> make: *** Waiting for unfinished jobs....
> |
>
> We have been ignoring it so I think it's safe to merge this commit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/501#issuecomment-95930967>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
These commits have been merged.

**Comment by QuLogic** [comment]
> Aborting due to internal error.

Could there be too many running in parallel and causing OOM troubles?

**Comment by komatits** [comment]
Good point; if this happens with make -j 8 but not with make -j 1 you 
are right, this could be the reason.

On 04/24/2015 10:29 PM, Elliott Sales de Andrade wrote:
>     Aborting due to internal error.
>
> Could there be too many running in parallel and causing OOM troubles?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/501#issuecomment-96055493>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
