### PR TITLE
Change a flag in specfem3d src + all changes for UTILS in Axisem dir

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 409](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/409). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by durochat** [comment]
Ok I know why, I fix that.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 410](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/410).

**Comment by komatits** [comment]
accept

On 12/14/2015 06:27 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 410
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/410>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/675#issuecomment-164502314>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
The `DATA/Par_file` used to be a symlink, but it is no longer so after this PR. I'm not sure if the new one is in sync with the old target.

**Comment by durochat** [comment]
Weird because it's a new fork and "git pull" is in my alias for every PR... 
But yes it used to be a simlink pointing to a Par_file of one the examples.
I can restore it tomorrow, but, do is it really necessary to restore this simlink (given that every example script copy its own Par_file to this Par_file) ?
If yes, how I can see please to which Par_file it was a simlink ?

Thanks,
Clément.

**Comment by komatits** [comment]
Hi Clément,

Yes, it is better to restore the symlink in order to maintain a single 
file instead of two copies.
The link was:

lrwxrwxrwx  1    84 Jun 22 17:09 Par_file -> 
../EXAMPLES/homogeneous_halfspace_HEX8_elastic_absorbing_Stacey_5sides/DATA/Par_file


Best,
Dimitri.

On 12/14/2015 10:53 PM, Clément Durochat wrote:
> Weird because it's a new fork and "git pull" is in my alias for every PR...
> But yes it used to be a simlink pointing to a Par_file of one the examples.
> I can restore it tomorrow, but, do is it really necessary to restore
> this simlink (given that every example script copy its own Par_file to
> this Par_file) ?
> If yes, how I can see please to which Par_file it was a simlink ?
>
> Thanks,
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/675#issuecomment-164571338>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
OK perfect, I restore that tomorrow (and I have others PR to do too).

Thanks,
Clément.

2015-12-15 0:29 GMT+01:00 Dimitri Komatitsch <notifications@github.com>:

**Pull request merged**
