### PR TITLE
better flags.guess for gfortran; fixed a warning in src/specfem3D/fault_solver_dynamic.f90 detected by this new flags.guess

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 249](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/249). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 250](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/250).

**Comment by komatits** [comment]
accept

On 02/26/2015 02:29 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 250
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/250>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/437#issuecomment-76105638>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
