### PR TITLE
multiple updates (configuration, travis, ADIOS, GEOCUBIT, double-precision runs, code formatting)

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 894](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/894). Please fix the problems and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 895](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/895).

**Comment by danielpeter** [comment]
accept



On 10 Apr 2021, at 12:37 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 895<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/895__;!!Nmw4Hv0!g03REfYBFJoto1UNu2EJT7Oi9oRv7IG8J-dIJzmEHxVJtreblsyo3sxMXJ819dJCWysHBg$>.

**Pull request merged**
