### PR TITLE
Tutorial fixes as new pull request

### PR DESCRIPTION
**Pull request by gassmoeller**
These are all the fixes in the closed pull requests by @foivoskar, @liuqinya, @carltape, and @ykane. (#1537,#1538,#1539,#1540).

All: Sorry that your PRs were closed automatically, this was a consequence of the improvised nature of the tutorial, we had not considered what would happen if everyone made changes at the same time on the same branch. We will think about how to improve this process. 

I have taken all of your commits and integrated them into this pull request. So although it will appear as my pull request, you will still be listed as authors in specfem's git history and you do not need to redo your changes.

@ykane: I have a question about your change, you deleted the file EXTERNAL_PACKAGES_coupled_with_SPECFEM3D/AxiSEM_for_SPECFEM3D/UTILS_COUPLING_SpecFEM/config.h instead of moving it into the new directory. Was that on purpose or an accident? I can add it again here if necessary.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 932](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/932).

**Comment by danielpeter** [comment]
accept

**Comment by danielpeter** [comment]
great, thanks Rene for putting it all together!

**Pull request merged**
