### PR TITLE
removed old comments

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 218](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/218). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
I am not sure if GitHub allows attachment so I have posted the log file
here:
http://geoweb.princeton.edu/~luet/results.log
Obviously, I should think of a way to make the posting automatic.

On Fri, Feb 6, 2015 at 10:03 PM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 218
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/218>.
> Fix your mistakes and push your changes back to your branch
> komatits/specfem3d:devel. This pull-request will be reopened automatically.
> You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/386#issuecomment-73347039>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
Thanks! Fixed. (a use statement that was after an implicit none instead 
of before; some compilers accept that, others do not)

On 02/07/2015 05:25 AM, David Luet wrote:
> I am not sure if GitHub allows attachment so I have posted the log file
> here:
> http://geoweb.princeton.edu/~luet/results.log
> Obviously, I should think of a way to make the posting automatic.
>
> On Fri, Feb 6, 2015 at 10:03 PM, buildbot-princeton <
> notifications@github.com> wrote:
>
>  > Your changes failed the buildbot test. See build 218
>  >
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/218>.
>  > Fix your mistakes and push your changes back to your branch
>  > komatits/specfem3d:devel. This pull-request will be reopened
> automatically.
>  > You don't need to create a new pull request
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/386#issuecomment-73347039>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/386#issuecomment-73349261>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 219](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/219).

**Comment by komatits** [comment]
accept

On 02/07/2015 01:05 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 219
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/219>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/386#issuecomment-73361622>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
