### PR TITLE
Test (remove an useless space)

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 408](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/408).

**Comment by komatits** [comment]
if possible please avoid such tests, following 
https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM is 
sufficient.

Thanks,
Dimitri.

On 12/14/2015 04:27 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 408
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/408>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/674#issuecomment-164466701>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
reject

On 12/14/2015 04:27 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 408
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/408>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/674#issuecomment-164466701>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
