### PR TITLE
removed old copy of AxiSEM, as requested by several developers (there was no reason to have one, and it was making the code more complex for no reason)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 476](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/476). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 477](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/477). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 478](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/478).

**Comment by komatits** [comment]
accept

On 01/05/2016 18:34, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 478
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/478>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/754#issuecomment-216054041>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
