### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by Huihuiweng**
Added parallel decomposition of mesh with faults

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 912](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/912).

**Comment by danielpeter** [comment]
great, looks all good!

good idea also to include an example :) I'll change the `srun ..` command line to the `mpirun ..` line in that example though to be able to use it as a test example for workstations and CI on jenkins/VM nodes.

**Comment by danielpeter** [comment]
accept



On 5 Jul 2021, at 12:24 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 912<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/912__;!!Nmw4Hv0!hYtJ5U-Z4cvRDAQVIuHpJ9bdnZ0Nr3ppLzrfgcYOLpPlQKhEk3gUttnzos77yusivyyuwQ$>.

**Pull request merged**
