### PR TITLE
updates headers in source files and program names

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 431](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/431). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 432](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/432). Fix your mistakes and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
well, looks like buildbot is still broken at the moment (produces wrong patches)...

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 433](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/433).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
Hi Daniel,

You will likely need to redo it tomorrow, since the repository has a 
problem.

Best,
Dimitri.

On 02/11/2016 02:26 PM, daniel peter wrote:
> accept
>
>  > On Feb 11, 2016, at 3:53 PM, buildbot-princeton
> <notifications@github.com> wrote:
>  >
>  > Your changes passed the buildbot test. See build 433
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/433>.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/696#issuecomment-182849528>.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/696#issuecomment-182861735>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
