### PR TITLE
add one comment in get_force.f90

### PR DESCRIPTION
**Pull request by xiezhinan**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 356](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/356).

**Comment by xiezhinan** [comment]
I think it is maybe better give the information about the evolution of all the input files.

**Comment by komatits** [comment]
accept

On 06/23/2015 03:30 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 356
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/356>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/583#issuecomment-114318979>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
