### PR TITLE
added Python scripts to the list of files to clean in utils/clean_listings_specfem.pl; added files in the root directory to the list of files to clean in utils/clean_listings_specfem.pl

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 02/10/2015 12:22 AM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/397#issuecomment-73612865>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
Note, you are missing several really deep files in `utils`. A recursive search for files is generally better done using `find`, e.g.,
```
find . -regextype posix-extended -regex '.*\.(bash|c|csh|cu|fh|f90|F90|h|h\.in|pl|py|tex|txt|sh)'
```
This finds several missed files in `src/decompose_mesh/scotch_5.1.12b/...`, `utils/ADJOINT_TOMOGRAPHY_TOOLS/...`, `utils/DSM_FOR_SPECFEM3D/...`, etc.

**Comment by komatits** [comment]
Unfortunately that does not work (I tried, in 
utils/clean_listings_specfem.pl), the command tries to follow symlinks 
and also tries to clean things in the .git directory

thus -type f should be added, and also something to exclude the .git 
directory

On 02/10/2015 01:26 AM, Elliott Sales de Andrade wrote:
> Note, you are missing several really deep files in |utils|. A recursive
> search for files is generally better done using |find|, e.g.,
>
> |find . -regextype posix-extended -regex '.*\.(bash|c|csh|cu|fh|f90|F90|h|h\.in|pl|py|tex|txt|sh)'
> |
>
> This finds several missed files in
> |src/decompose_mesh/scotch_5.1.12b/...|,
> |utils/ADJOINT_TOMOGRAPHY_TOOLS/...|, |utils/DSM_FOR_SPECFEM3D/...|, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/397#issuecomment-73620892>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
The default behaviour is to not follow symlinks; it shouldn't act differently from the `ls` (which in fact included the symlinks, too.) Also, I don't think there should be anything with those extensions in the `.git` directory, but the `m4` directory should probably be ignored. You can ignore stuff with `-name '.git' -prune`.

So,
```
find . -name '.git' -prune -o \
       -name 'm4' -prune -o \
       -type f \
       -regextype posix-extended \
       -regex '.*\.(bash|c|csh|cu|fh|f90|F90|h|h\.in|pl|py|tex|txt|sh)' \
       -print
```

**Comment by komatits** [comment]
Thanks! We are getting close. Any idea about why other files (for 
instance configure.ac) appear in the list of files found, not only those 
ending in .(bash|c|csh|cu|fh|f90|F90|h|h\.in|pl|py|tex|txt|sh)?
It seems the find command below looks for *.*c instead of only *.c, 
since we get *.ac files in the list for instance.

Thanks,
Dimitri.

On 02/10/2015 02:26 AM, Elliott Sales de Andrade wrote:
> The default behaviour is to not follow symlinks; it shouldn't act
> differently from the |ls| (which in fact included the symlinks, too.)
> Also, I don't think there should be anything with those extensions in
> the |.git| directory, but the |m4| directory should probably be ignored.
> You can ignore stuff with |-name '.git' -prune|.
>
> So,
>
> |find . -name '.git' -prune -o \
>         -name 'm4' -prune -o \
>         -type f \
>         -regextype posix-extended \
>         -regex '.*\.(bash|c|csh|cu|fh|f90|F90|h|h\.in|pl|py|tex|txt|sh)' \
>         -print
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/397#issuecomment-73627293>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
I do not see `configure.ac` in the result; maybe you missed the backslash before the dot when copying?

**Comment by komatits** [comment]
It is when I include it in the Perl script that I get configure.ac in 
the list; let me email you the script.

On 02/10/2015 10:06 PM, Elliott Sales de Andrade wrote:
> I do not see |configure.ac| in the result; maybe you missed the
> backslash before the dot when copying?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/397#issuecomment-73783571>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Fixed by Elliott (an additional \ is needed when using the command from 
Perl). I will commit the new script in a few minutes.

On 02/10/2015 10:28 PM, Dimitri Komatitsch wrote:
>
> It is when I include it in the Perl script that I get configure.ac in
> the list; let me email you the script.
>
> On 02/10/2015 10:06 PM, Elliott Sales de Andrade wrote:
>> I do not see |configure.ac| in the result; maybe you missed the
>> backslash before the dot when copying?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/397#issuecomment-73783571>.
>>
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
