### PR TITLE
renamed src/tomography/sum_kernels.f90 to src/tomography/sum_kernels_old_deprecated.f90

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 244](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/244). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by komatits** [comment]
Canceled (replaced with a new pull request).

**Pull request closed without merging**
