### PR TITLE
prepares gpu routines for more kernels; updates mostly fault routines, adds rate and state friction support (and fixes issues) in gpu version

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 887](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/887). Please fix the problems and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 888](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/888). Please fix the problems and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 889](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/889).

**Comment by danielpeter** [comment]
accept


On Mar 4, 2021, at 02:04, buildbot-princeton <notifications@github.com<mailto:notifications@github.com>> wrote:


Your changes passed the buildbot test. See build 889<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/889__;!!Nmw4Hv0!g4MQ6zoWUE4XSnpBHBfUoYo20MI-xXBpG8sXSNbd4Ej8B8EWVA3l-NBxQcdVHYRJyBR1Tw$>.

**Pull request merged**
