### PR TITLE
coupling with AxiSEM using meshfem3D staigjt chunk with doubling

### PR DESCRIPTION
**Pull request by vmont**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 382](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/382). Fix your mistakes and push your changes back to your branch vmont/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 383](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/383).

**Comment by komatits** [comment]
accept

On 09/26/2015 01:14 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 383
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/383>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/634#issuecomment-143421991>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
