### PR TITLE
Add option to use bottom zmin as free surface which is needed in some ultrasonic modeling

### PR DESCRIPTION
**Pull request by vmont**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 489](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/489). Fix your mistakes and push your changes back to your branch vmont/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 490](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/490).

**Comment by komatits** [comment]
accept

On 03/06/2016 19:21, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 490
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/490>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/767#issuecomment-223639658>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKZurrmedeboaPwxw1asdB1H5FWcSks5qIGKQgaJpZM4ItuUX>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
