### PR TITLE
updates seismogram output

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by danielpeter** [comment]
accept



On 14 Sep 2020, at 6:14 PM, buildbot-princeton <notifications@github.com<mailto:notifications@github.com>> wrote:



Your changes passed the buildbot test. See build 877<http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/877>.

**Comment by bottero** [comment]
Nice! Thank you Daniel!

If you have the time and energy option subsamp_seismos (like in the 2d
version: saving only one time step every subsamp time steps at the
receivers) would be amazingly helpful as well. When outputting a lot of
signals (3*velocity+pressure for ex), at many different positions and for
many time steps the memory of our poor gpus gets filled very quickly for no
reason (sampling way above Nyquist).
I have it on my TODO list for a long time but I've been overwhelmed with
many things... :(

Thank you so much for your work,

Cheers,

Alexis Bottero
Marine Physical Laboratory
Scripps Institution of Oceanography
(+1) 619 677 9887
(+33) 695 170 097

**Comment by danielpeter** [comment]
hi Alexis, let me look into it. how many timesteps and receivers would you have typically? just to get an idea of the size of the arrays...

**Comment by bottero** [comment]
Hi Daniel,
Oh, I have already personally worked with two thousand receivers and a
million time steps saving the pressure and the three components of
velocity... (tens of Gb) But I am sure it could be even worse!

Alexis Bottero
Marine Physical Laboratory
Scripps Institution of Oceanography
(+1) 619 677 9887
(+33) 695 170 097


Le mar. 15 sept. 2020 à 11:54, daniel peter <notifications@github.com> a
écrit :

**Comment by bottero** [comment]
Thank you so much for looking into this!

Alexis Bottero
Marine Physical Laboratory
Scripps Institution of Oceanography
(+1) 619 677 9887
(+33) 695 170 097


Le mar. 15 sept. 2020 à 14:24, Alexis Bottero <alexis.bottero@gmail.com> a
écrit :

**Pull request merged**
