### PR TITLE
fixes ADIOS with variable array sizes, simultaneous runs, boundary wavefield injection

### PR DESCRIPTION
**Pull request by danielpeter**
ADIOS wavefield compression for undo_att snapshot files has corresponding options in constants.h file

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/shared/adios_manager.F90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/shared/adios_manager.F90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/shared/adios_manager.F90-o src/shared/adios_manager.F90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 919](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/919).

**Comment by danielpeter** [comment]
accept

On 6 Mar 2022, at 10:32 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 919<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/919__;!!Nmw4Hv0!i06fQNOZPOoftPPwXWAQkpLYIJ9AO6-i6pg71tdG4zUsOb4GQYDi7-cW2ytuwm9piRohzw$>.

**Pull request merged**
