### PR TITLE
Reciprocity : general surface integral OK

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 302](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/302). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by durochat** [comment]
I don't understand I don't have any error or warning when I compile on Curie or local cluster of Marseille. It says that the module specfem_par can't be opened in the new routine committed here.
The line with this error is just : "use specfem_par", as many other...

Is there a problem for that with Openmp ?

**Comment by luet** [comment]
Just for the info, I haven't migrated specfem3d to gfortran 4.8.2.
In fact I haven't changed specfem3d's buildbot in a while.

On Thu, Apr 30, 2015 at 1:05 PM, Clément Durochat <notifications@github.com>
wrote:

> I don't understand I don't have any error or warning when I compile on
> Curie or local cluster of Marseille. It says that the module specfem_par
> can't be opened in the new routine committed here.
> The line with this error is just : "use specfem_par", as many other...
>
> Is there a problem for that with Openmp ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-97882721>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by durochat** [comment]
So it is normal that the buildbot test failed ?

**Comment by luet** [comment]
No it's not normal. I just didn't want people to wonder whether I had done
some changes to the buildbot config since I was working on specfem2d this
morning.
So I think there likely is a problem with your code.

On Thu, Apr 30, 2015 at 1:19 PM, Clément Durochat <notifications@github.com>
wrote:

> So it is normal that the buildbot test failed ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-97885467>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
When you say it compiles on your machine, are you saying that you
configured with:

     ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc
FCFLAGS=-fopenmp --with-openmp

On Thu, Apr 30, 2015 at 1:22 PM, David Luet <luet@princeton.edu> wrote:

> No it's not normal. I just didn't want people to wonder whether I had done
> some changes to the buildbot config since I was working on specfem2d this
> morning.
> So I think there likely is a problem with your code.
>
> On Thu, Apr 30, 2015 at 1:19 PM, Clément Durochat <
> notifications@github.com> wrote:
>
>> So it is normal that the buildbot test failed ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-97885467>
>> .
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by QuLogic** [comment]
It is not failing for you because you are not building in parallel. You need to add a dependency on `$O/specfem3D_par.spec.o` for the new file you just added, just like all the other files that use the module.

**Comment by komatits** [comment]
Hi Clément,

you need to configure the code with and without --with-mpi i.e. compile 
it twice before submitting a pull request because the code can be 
compiled in serial mode or in MPI mode.

It seems that in your current pull request you will get compiler error 
messages in one of the two cases, which you did not test.

BuildBot tests both and thus rejects your request (rightfully so).

Best,
Dimitri.

On 04/30/2015 07:26 PM, David Luet wrote:
> When you say it compiles on your machine, are you saying that you
> configured with:
>
> ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc
> FCFLAGS=-fopenmp --with-openmp
>
> On Thu, Apr 30, 2015 at 1:22 PM, David Luet <luet@princeton.edu> wrote:
>
>  > No it's not normal. I just didn't want people to wonder whether I had
> done
>  > some changes to the buildbot config since I was working on specfem2d this
>  > morning.
>  > So I think there likely is a problem with your code.
>  >
>  > On Thu, Apr 30, 2015 at 1:19 PM, Clément Durochat <
>  > notifications@github.com> wrote:
>  >
>  >> So it is normal that the buildbot test failed ?
>  >>
>  >> —
>  >> Reply to this email directly or view it on GitHub
>  >>
> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-97885467>
>  >> .
>  >>
>  >
>  >
>  >
>  > --
>  > David Luet
>  > Linux Administrator/Software & Programming Analyst
>  > Department of Geosciences & PICSciE
>  > Princeton University
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-97888028>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
Hi all, thank you for your help ! 

I compiled without MPI, with MPI, and with OpenMP, and on the clusters I use, it is ok.
But effectively, as Elliot says, I didn't add a line for depency in rules.mk : it does not give error on the clusters I use, but apprently it is a problem for the buildbot.

So I add the line in rules.mk, and I try a new buildbot test (but I'm not sure it will ok)

Thank you very much,
Clément.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 303](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/303).

**Comment by durochat** [comment]
Perfect! So the problem was indeed the line of depency, but it's weird that it gave no error from my side...

Thanks,
Clément.

**Comment by QuLogic** [comment]
Parallel build issues are highly difficult to reproduce because you need to have a system that is capable of high build parallelism. If your system is too slow (because of I/O, most likely), you may not see it. That's why BuildBot checks it.

**Comment by komatits** [comment]
accept

On 05/03/2015 10:38 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 303
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/303>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/505#issuecomment-98541541>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
