### PR TITLE
Delete useless files

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 378](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/378). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by durochat** [comment]
I don't understand the error. It's not a compilation error, so maybe the PR is too huge ??

Thanks,
Clément.

**Comment by durochat** [comment]
@luet : Would you know where the error is? I don't know which modification I have to do to fix the mistake...

Thank you very much,
Clément.

**Comment by luet** [comment]
It was a problem on my side. It's fixed now. I have also merged the PR.
See build 379
<http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/379>
.
David

On Mon, Sep 21, 2015 at 11:18 AM, Clément Durochat <notifications@github.com
> wrote:

> @luet <https://github.com/luet> : Would you know where the error is? I
> don't know which modification I have to do to fix the mistake...
>
> Thank you very much,
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/628#issuecomment-142012922>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by durochat** [comment]
Ok perfect, thanks you !

Best,
Clément.

**Pull request merged**
