### PR TITLE
corrected typos

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by rmodrak** [comment]
There seems to be a problem with this pull request.  Let me try closing and resubmitting again.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 260](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/260).

**Comment by luet** [comment]
@rmodrak What do you think the problem is?

On Thu, Mar 5, 2015 at 11:33 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes passed the buildbot test. See build 260
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/260>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/446#issuecomment-77397385>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
accept

On 03/05/2015 05:33 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 260
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/260>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/446#issuecomment-77397385>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
