### PR TITLE
Correct bug in save arrays solver ofr coupling with DSM

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 199](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/199). Fix your mistakes and push your changes back to your branch durochat/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 200](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/200).

**Comment by komatits** [comment]
accept

On 01/16/2015 05:48 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 200
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/200>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/354#issuecomment-70282866>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
