### PR TITLE
removed compiler option -lrt from Scotch because it was useless and could lead to linking errors on some Mac OS systems

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 02/11/2016 05:08 PM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182936818>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKc5eVzFvA9aM5THKEEWptLGB7iYpks5pjKmZgaJpZM4HYSKc.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by luet** [comment]
I am looking into it.

On Thu, Feb 11, 2016 at 11:12 AM, buildbot-princeton <
notifications@github.com> wrote:

> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182938371>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 434](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/434).

**Comment by luet** [comment]
accept

On Thu, Feb 11, 2016 at 11:18 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes passed the buildbot test. See build 434
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/434>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940265>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
I have not received the "Merged" email. Is there a remaining problem 
somewhere?

Thanks,
Dimitri.

On 02/11/2016 05:20 PM, David Luet wrote:
> accept
>
> On Thu, Feb 11, 2016 at 11:18 AM, buildbot-princeton <
> notifications@github.com> wrote:
>
>  > Your changes passed the buildbot test. See build 434
>  >
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/434>
>  > .
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940265>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940927>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
It's ok. It has been merged. The problem was that my local mirrors were out
of sync following the problem we had this morning.
David

On Thu, Feb 11, 2016 at 11:51 AM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> I have not received the "Merged" email. Is there a remaining problem
> somewhere?
>
> Thanks,
> Dimitri.
>
> On 02/11/2016 05:20 PM, David Luet wrote:
> > accept
> >
> > On Thu, Feb 11, 2016 at 11:18 AM, buildbot-princeton <
> > notifications@github.com> wrote:
> >
> > > Your changes passed the buildbot test. See build 434
> > >
> > <
> http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/434
> >
> > > .
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940265>
> > > .
> > >
> >
> >
> >
> > --
> > David Luet
> > Linux Administrator/Software & Programming Analyst
> > Department of Geosciences & PICSciE
> > Princeton University
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940927>.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182955243>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Thanks!

Dimitri.

On 02/11/2016 05:54 PM, David Luet wrote:
> It's ok. It has been merged. The problem was that my local mirrors were out
> of sync following the problem we had this morning.
> David
>
> On Thu, Feb 11, 2016 at 11:51 AM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  >
>  > I have not received the "Merged" email. Is there a remaining problem
>  > somewhere?
>  >
>  > Thanks,
>  > Dimitri.
>  >
>  > On 02/11/2016 05:20 PM, David Luet wrote:
>  > > accept
>  > >
>  > > On Thu, Feb 11, 2016 at 11:18 AM, buildbot-princeton <
>  > > notifications@github.com> wrote:
>  > >
>  > > > Your changes passed the buildbot test. See build 434
>  > > >
>  > > <
>  >
> http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/434
>  > >
>  > > > .
>  > > >
>  > > > —
>  > > > Reply to this email directly or view it on GitHub
>  > > >
>  > > <
>  > https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940265>
>  > > > .
>  > > >
>  > >
>  > >
>  > >
>  > > --
>  > > David Luet
>  > > Linux Administrator/Software & Programming Analyst
>  > > Department of Geosciences & PICSciE
>  > > Princeton University
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182940927>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182955243>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/697#issuecomment-182956506>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
