### PR TITLE
added contribution from Florian Schumacher in Germany: added a call to model_default before calling model_external_values in order to be able to superimpose a model onto the default one

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 355](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/355).

**Comment by komatits** [comment]
accept

On 06/22/2015 05:02 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 355
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/355>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/579#issuecomment-114142284>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
FYI, `git commit --author='Florian Schumacher <...@email.com>'`. You will be committer, but he will get authorship.

**Pull request merged**
