### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 442](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/442). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by kbai** [comment]
I don't what the error is. It seems to be an internal error that I cannot handle.

**Comment by QuLogic** [comment]
Yes, I think @luet will just have to redo that build.

**Comment by luet** [comment]
I just reran it and it passed: [build 443](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/443)

**Comment by kbai** [comment]
Thank you!

**Comment by komatits** [comment]
Merged manually, since BuildBot dit not merge it.

**Pull request merged**
