### PR TITLE
added DATA/detect_duplicates_stations_file.f90

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 214](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/214).

**Comment by komatits** [comment]
accept

On 02/03/2015 03:47 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 214
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/214>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/381#issuecomment-72662261>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
In `DATA`? Wouldn't this fit better in `src/auxiliaries`? It could be added to the makefile there.

**Comment by komatits** [comment]
done

On 02/04/2015 03:25 AM, Elliott Sales de Andrade wrote:
> In |DATA|? Wouldn't this fit better in |src/auxiliaries|? It could be
> added to the makefile there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/381#issuecomment-72778826>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
