### PR TITLE
Organisation of DSM directory for Nobu modifs => done

### PR DESCRIPTION
**Pull request by durochat**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 200](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/200).

**Comment by luet** [comment]
Something went wrong with buildbot. It didn't test the write patch. Let me run it by hand and investigate before accepting.

**Comment by durochat** [comment]
Yes, the message "Your changes passed the buildbot test. See build 200." came before "The files changed require a buildbot test. Buildbot has started.", not as usual... 

Thanks,
Clément.

**Comment by komatits** [comment]
accept

On 01/19/2015 03:02 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 200
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/200>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70496014>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi,

I saw your message too late and had already accepted it after receiving 
the buildbot message. sorry

Dimitri

On 01/19/2015 03:28 PM, David Luet wrote:
> Something went wrong with buildbot. It didn't test the write patch. Let
> me run it by hand and investigate before accepting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70500308>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
So, it is ok even if the buildbot didn't test the write patch ? Theses commits only concern the directory DSM_FOR_SPECFEM3D, not directly the sources of specfem...

Clément.

**Comment by luet** [comment]
Yes it looks ok see build 203
<http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/203>
.

They were a lot of trailing white spaces that were reported. For examples:
utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-1a-compute_DSM_coefficients_with_FEMs_SH/makefile_old
utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2a-read_DSM_coefficients_back_SH/TraPSV_MPI_read_Zmin/TraSH-0.1.0.f90
utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2a-read_DSM_coefficients_back_SH/TraPSV_MPI_read_Zmin/calmat.f90

The reason I mention it is that even running the beautifier doesn't get rid
of them.



On Mon, Jan 19, 2015 at 11:06 AM, Clément Durochat <notifications@github.com
> wrote:

> So, it is ok even if the buildbot didn't test the write patch ? Theses
> commits only concern the directory DSM_FOR_SPECFEM3D, not directly the
> sources of specfem...
>
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70517811>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by durochat** [comment]
Okay, thanks !

Clément.

**Comment by luet** [comment]
So I figured out why buildbot failed initially: they are some non-ASCII
characters in the commit. Specifically, I think git patches, which I use
for buildbot, don't handle non ASCII characters. I'll keep looking for the
actual specifications.

I have posted two patches for Clément's commit for this PR, on an external
web site: http://geoweb3.princeton.edu/~luet/patch_ascii_pb/
<http://geoweb3.princeton.edu/~luet/patch_ascii_pb/>
- specfem3d.patch: is the original patch
- specfem3d_ASCII.patch: is the patch scrubbed of non-ASCII characters.
Do a diff to find the non-ASCII characters.

They are some French accents and some degree symbols but also if you look
at line 581 of:
utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2b-read_DSM_coefficients_back_PSV/TraPSV_MPI_read_Zmin/TraPSV-0.1.3.f90

There are characters that I assume should be underscores but are not, i.e.
the character between the first ! and 3 on that line.

On Linux, the command I used to scrub the non-ASCII characters is:

iconv -f utf-8 -t ASCII//TRANSLIT specfem3d.patch -o specfem3d_ASCII.patch
I have a sense that the safest way for us is to stick with ASCII
characters. So I was thinking that I could either
1) write a script to automatically replace the non-ASCII characters,
2) detect non-ASCII characters and reject the pull-request.

I think we should clean Clément's commit. @durochat: can I let you do it?

Let me know what you think.

Best,
David



On Mon, Jan 19, 2015 at 11:40 AM, Clément Durochat <notifications@github.com
> wrote:

> Okay, thanks !
>
> Clément.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70523411>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Hi,

that's normal, the beautifier processes the content of a given file but 
does not change the name of the file. (and should not)

Clément, please avoid mixing - and _ in file names, that makes no sense. 
Please use underscores only i.e. _

thanks
Dimitri

On 01/19/2015 05:22 PM, David Luet wrote:
> Yes it looks ok see build 203
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/203>
>
> .
>
> They were a lot of trailing white spaces that were reported. For examples:
> utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-1a-compute_DSM_coefficients_with_FEMs_SH/makefile_old
>
> utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2a-read_DSM_coefficients_back_SH/TraPSV_MPI_read_Zmin/TraSH-0.1.0.f90
>
> utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2a-read_DSM_coefficients_back_SH/TraPSV_MPI_read_Zmin/calmat.f90
>
>
> The reason I mention it is that even running the beautifier doesn't get rid
> of them.
>
>
>
> On Mon, Jan 19, 2015 at 11:06 AM, Clément Durochat
> <notifications@github.com
>  > wrote:
>
>  > So, it is ok even if the buildbot didn't test the write patch ? Theses
>  > commits only concern the directory DSM_FOR_SPECFEM3D, not directly the
>  > sources of specfem...
>  >
>  > Clément.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70517811>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70520420>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi David,

in such a case let us reject the request but inform the user where the 
problem is, and give him/her the Unix command below to get rid of the 
non-ASCII characters; this way little by little users will stop 
committing non-ASCII stuff

thanks
Dimitri.

On 01/19/2015 06:25 PM, David Luet wrote:
> So I figured out why buildbot failed initially: they are some non-ASCII
> characters in the commit. Specifically, I think git patches, which I use
> for buildbot, don't handle non ASCII characters. I'll keep looking for the
> actual specifications.
>
> I have posted two patches for Clément's commit for this PR, on an external
> web site: http://geoweb3.princeton.edu/~luet/patch_ascii_pb/
> <http://geoweb3.princeton.edu/~luet/patch_ascii_pb/>
> - specfem3d.patch: is the original patch
> - specfem3d_ASCII.patch: is the patch scrubbed of non-ASCII characters.
> Do a diff to find the non-ASCII characters.
>
> They are some French accents and some degree symbols but also if you look
> at line 581 of:
> utils/DSM_FOR_SPECFEM3D/DSM-1-BIG_3D_storage_version/Part-2b-read_DSM_coefficients_back_PSV/TraPSV_MPI_read_Zmin/TraPSV-0.1.3.f90
>
>
> There are characters that I assume should be underscores but are not, i.e.
> the character between the first ! and 3 on that line.
>
> On Linux, the command I used to scrub the non-ASCII characters is:
>
> iconv -f utf-8 -t ASCII//TRANSLIT specfem3d.patch -o specfem3d_ASCII.patch
> I have a sense that the safest way for us is to stick with ASCII
> characters. So I was thinking that I could either
> 1) write a script to automatically replace the non-ASCII characters,
> 2) detect non-ASCII characters and reject the pull-request.
>
> I think we should clean Clément's commit. @durochat: can I let you do it?
>
> Let me know what you think.
>
> Best,
> David
>
>
>
> On Mon, Jan 19, 2015 at 11:40 AM, Clément Durochat
> <notifications@github.com
>  > wrote:
>
>  > Okay, thanks !
>  >
>  > Clément.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70523411>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70530164>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
@luet How are you getting the patches? I don't think there should be a problem with accents; probably the two systems just aren't using the same encoding?

@durochat Please configure your editor to strip trailing spaces. You might also want to look into running Dimitri's formatting script as well (or perhaps figure out what it does and write code directly in that style.) That will save buildbot from adding an extra cleanup commit after merging your PRs.

**Comment by komatits** [comment]
Hi,

it is better to get rid of accents anyway; they are not standard, and 
one of our main goals is portability

thanks
dimitri

On 01/19/2015 10:43 PM, Elliott Sales de Andrade wrote:
> @luet <https://github.com/luet> How are you getting the patches? I don't
> think there should be a problem with accents; probably the two systems
> just aren't using the same encoding?
>
> @durochat <https://github.com/durochat> Please configure your editor to
> strip trailing spaces. You might also want to look into running
> Dimitri's formatting script as well (or perhaps figure out what it does
> and write code directly in that style.) That will save buildbot from
> adding an extra cleanup commit after merging your PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70566499>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
It turns out I spoke to fast. The problem was not with the character set
but with the size of the patch. The limitation comes from twisted that
buildbot uses as a networking engine. I had already made a patched version
of twisted but that's not the one I was using. It's fixed now.

In any case I think we should stick with ASCII just to be conservative.


On Mon, Jan 19, 2015 at 4:43 PM, Elliott Sales de Andrade <
notifications@github.com> wrote:

> @luet <https://github.com/luet> How are you getting the patches? I don't
> think there should be a problem with accents; probably the two systems just
> aren't using the same encoding?
>
> @durochat <https://github.com/durochat> Please configure your editor to
> strip trailing spaces. You might also want to look into running Dimitri's
> formatting script as well (or perhaps figure out what it does and write
> code directly in that style.) That will save buildbot from adding an extra
> cleanup commit after merging your PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70566499>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Yes, I agree, let us stick with ASCII; you can add the Linux command you 
sent to the beautifier (whose source code is in 
specfem3d/utils/clean_listings_specfem.pl )

Thanks,
Dimitri.

On 01/20/2015 09:56 PM, David Luet wrote:
> It turns out I spoke to fast. The problem was not with the character set
> but with the size of the patch. The limitation comes from twisted that
> buildbot uses as a networking engine. I had already made a patched version
> of twisted but that's not the one I was using. It's fixed now.
>
> In any case I think we should stick with ASCII just to be conservative.
>
>
> On Mon, Jan 19, 2015 at 4:43 PM, Elliott Sales de Andrade <
> notifications@github.com> wrote:
>
>  > @luet <https://github.com/luet> How are you getting the patches? I don't
>  > think there should be a problem with accents; probably the two
> systems just
>  > aren't using the same encoding?
>  >
>  > @durochat <https://github.com/durochat> Please configure your editor to
>  > strip trailing spaces. You might also want to look into running
> Dimitri's
>  > formatting script as well (or perhaps figure out what it does and write
>  > code directly in that style.) That will save buildbot from adding an
> extra
>  > cleanup commit after merging your PRs.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70566499>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/355#issuecomment-70731457>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
