### PR TITLE
GPU fault solver. Implement the rate and state friction solver on CUDA.

### PR DESCRIPTION
**Pull request by kbai**
Currently only on rate and state friction.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 388](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/388). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 389](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/389). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 390](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/390). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 391](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/391).

**Comment by komatits** [comment]
accept

On 10/12/2015 04:13 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 391
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/391>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/642#issuecomment-147273984>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
