### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes cannot be merged with a fast-forward merge.
This indicates that your repo is out of sync with the central repo.
If you are using hub, do:
$ git pull
If your are not using hub, do:
$ git pull upstream devel
Then open a new pull-request.

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
accept

On 02/11/2016 02:34 AM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182668494>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 430](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/430). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Seems to be a BuildBot issue

**Comment by QuLogic** [comment]
@luet Maybe BuildBot is confused because it was a non-fast forward PR and now it is?

@komatits Also, it seems like you forgot to set your username/email on the git client you're using.

**Comment by komatits** [comment]
Yes, something weird happened. I did type git pull before git commit 
though, thus I do not understand why there was this issue with fast 
forward; first time I see this.

Could it be that BuildBot ran the beautifier in between? (in the few 
seconds between my git pull and my git commit?)

Regarding the user name and email it should be fixed but let me check 
because I switched to a new laptop and thus I do not remember how to 
configure that.

I will also check my new install of 'hub' to alias 'git'. What we say at 
https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM#install-hub 
did not work, it complained about a compiler called "go" that was 
missing (I then installed gccgo but still got the same error); I thus 
downloaded one of their precompiled binaries, which seemed to work (?). 
And I successfully used it for other pull requests in the 2D code...

Thanks,
Dimitri.

On 02/11/2016 04:05 AM, Elliott Sales de Andrade wrote:
> @luet <https://github.com/luet> Maybe BuildBot is confused because it
> was a non-fast forward PR and now it is?
>
> @komatits <https://github.com/komatits> Also, it seems like you forgot
> to set your username/email on the git client you're using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182680082>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
Yes the hub script is now written in Go. We have used the precompiled
version for close to 6 months and we haven't had any issue.
I can't be sure about what you did but my guess is that you hadn't pulled
the commit where buildbot ran the code beautifier. I had assumed in the
code that a closed PR would not be reopened. I am going to change the code
to take that into account.
David

On Thu, Feb 11, 2016 at 9:33 AM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> Yes, something weird happened. I did type git pull before git commit
> though, thus I do not understand why there was this issue with fast
> forward; first time I see this.
>
> Could it be that BuildBot ran the beautifier in between? (in the few
> seconds between my git pull and my git commit?)
>
> Regarding the user name and email it should be fixed but let me check
> because I switched to a new laptop and thus I do not remember how to
> configure that.
>
> I will also check my new install of 'hub' to alias 'git'. What we say at
>
> https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM#install-hub
> did not work, it complained about a compiler called "go" that was
> missing (I then installed gccgo but still got the same error); I thus
> downloaded one of their precompiled binaries, which seemed to work (?).
> And I successfully used it for other pull requests in the 2D code...
>
> Thanks,
> Dimitri.
>
> On 02/11/2016 04:05 AM, Elliott Sales de Andrade wrote:
> > @luet <https://github.com/luet> Maybe BuildBot is confused because it
> > was a non-fast forward PR and now it is?
> >
> > @komatits <https://github.com/komatits> Also, it seems like you forgot
> > to set your username/email on the git client you're using.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182680082>.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182889657>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Hi David,

OK, thanks! Then it is really a rare coincidence because I typed git 
pull and then a few seconds (or maybe a minute) later git push and then 
git pull request if I remember correctly. It seems the beautifier ran 
automatically in between. (?)

Thanks for fixing that!

Dimitri.

On 02/11/2016 03:51 PM, David Luet wrote:
> Yes the hub script is now written in Go. We have used the precompiled
> version for close to 6 months and we haven't had any issue.
> I can't be sure about what you did but my guess is that you hadn't pulled
> the commit where buildbot ran the code beautifier. I had assumed in the
> code that a closed PR would not be reopened. I am going to change the code
> to take that into account.
> David
>
> On Thu, Feb 11, 2016 at 9:33 AM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  >
>  > Yes, something weird happened. I did type git pull before git commit
>  > though, thus I do not understand why there was this issue with fast
>  > forward; first time I see this.
>  >
>  > Could it be that BuildBot ran the beautifier in between? (in the few
>  > seconds between my git pull and my git commit?)
>  >
>  > Regarding the user name and email it should be fixed but let me check
>  > because I switched to a new laptop and thus I do not remember how to
>  > configure that.
>  >
>  > I will also check my new install of 'hub' to alias 'git'. What we say at
>  >
>  >
> https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM#install-hub
>  > did not work, it complained about a compiler called "go" that was
>  > missing (I then installed gccgo but still got the same error); I thus
>  > downloaded one of their precompiled binaries, which seemed to work (?).
>  > And I successfully used it for other pull requests in the 2D code...
>  >
>  > Thanks,
>  > Dimitri.
>  >
>  > On 02/11/2016 04:05 AM, Elliott Sales de Andrade wrote:
>  > > @luet <https://github.com/luet> Maybe BuildBot is confused because it
>  > > was a non-fast forward PR and now it is?
>  > >
>  > > @komatits <https://github.com/komatits> Also, it seems like you forgot
>  > > to set your username/email on the git client you're using.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182680082>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182889657>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/695#issuecomment-182895637>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
