### PR TITLE
adds seismogram subsampling

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 879](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/879).

**Comment by danielpeter** [comment]
accept


On Sep 23, 2020, at 18:02, buildbot-princeton <notifications@github.com<mailto:notifications@github.com>> wrote:


Your changes passed the buildbot test. See build 879<http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/879>.

**Comment by bottero** [comment]
Amazing! This will be really useful I am sure!

Thank you so much,

Alexis Bottero
Marine Physical Laboratory
Scripps Institution of Oceanography
(+1) 619 677 9887
(+33) 695 170 097

**Comment by jwbishop** [comment]
As another user of SPECFEM3D, I also think this will be a useful addition. Thank you.

**Pull request merged**
