### PR TITLE
started to make the time iteration routine of SPECFEM3D and SPECFEM3D_GLOBE much closer

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 230](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/230). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 231](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/231). Fix your mistakes and push your changes back to your branch komatits/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Same as before, thus accepting it manually.

**Comment by luet** [comment]
I may have missed something but buildbot didn't complain about the same
error twice.
I posted the error log for the last error, here:
http://geoweb3.princeton.edu/~luet/results.log

On Sun, Feb 15, 2015 at 1:25 PM, Dimitri Komatitsch <
notifications@github.com> wrote:

> Merged #412 <https://github.com/geodynamics/specfem3d/pull/412>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/412#event-236011128>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
I have located the problem: "make all" does not do "make tests", thus 
"make all" can be OK but then BuildBot can detect a problem in the 
tests, which are untested by "make all" (i.e. "all" is not really all)

Let me fix the tests then.

On 02/15/2015 08:04 PM, David Luet wrote:
> I may have missed something but buildbot didn't complain about the same
> error twice.
> I posted the error log for the last error, here:
> http://geoweb3.princeton.edu/~luet/results.log
>
> On Sun, Feb 15, 2015 at 1:25 PM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  > Merged #412 <https://github.com/geodynamics/specfem3d/pull/412>.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/geodynamics/specfem3d/pull/412#event-236011128>.
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/412#issuecomment-74431324>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
`all` is the default target, so it's all _programs_ only. You don't want tests to run every time you recompile.

**Comment by komatits** [comment]
"make tests" fixed.


On 02/15/2015 09:04 PM, Dimitri Komatitsch wrote:
>
> I have located the problem: "make all" does not do "make tests", thus
> "make all" can be OK but then BuildBot can detect a problem in the
> tests, which are untested by "make all" (i.e. "all" is not really all)
>
> Let me fix the tests then.
>
> On 02/15/2015 08:04 PM, David Luet wrote:
>> I may have missed something but buildbot didn't complain about the same
>> error twice.
>> I posted the error log for the last error, here:
>> http://geoweb3.princeton.edu/~luet/results.log
>>
>> On Sun, Feb 15, 2015 at 1:25 PM, Dimitri Komatitsch <
>> notifications@github.com> wrote:
>>
>>  > Merged #412 <https://github.com/geodynamics/specfem3d/pull/412>.
>>  >
>>  > —
>>  > Reply to this email directly or view it on GitHub
>>  > <https://github.com/geodynamics/specfem3d/pull/412#event-236011128>.
>>  >
>>
>>
>>
>> --
>> David Luet
>> Linux Administrator/Software & Programming Analyst
>> Department of Geosciences & PICSciE
>> Princeton University
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/412#issuecomment-74431324>.
>>
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
