### PR TITLE
fixes elevation interpolations; updates asdf; adds analytical example

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 891](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/891). Please fix the problems and push your changes back to your branch danielpeter/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 892](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/892).

**Comment by danielpeter** [comment]
accept


On 27 Mar 2021, at 11:43 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 892<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/892__;!!Nmw4Hv0!ge99P2J3Jq-KaqidC4G4mwu3YDYe1WoHQIT7iXLDAB2Lqx7l9gdKOsownj-8AzXCfqueAA$>.

**Pull request merged**
