### PR TITLE
GPU fault solver slip weakening

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 395](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/395). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 396](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/396). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 397](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/397). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 398](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/398). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 399](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/399).

**Comment by komatits** [comment]
accept

On 11/12/2015 09:29 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 399
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/399>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/657#issuecomment-156032746>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
