### PR TITLE
updates examples and simulation checks; adds travis

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 494](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/494).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
accept

On 10/07/2016 20:45, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 494
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/494>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/778#issuecomment-231604250>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKScHBR2BTzTQUblxwI58ATRN5idAks5qUT3WgaJpZM4JI48O>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
