### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by Huihuiweng**
Minor edits of code and User_Manual for adding the exponential slip-weakening friction law

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 914](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/914).

**Review by danielpeter — CHANGES_REQUESTED** [review]
Please remove these files from your pull request:
- external_libs/scotch5.1.12b/src/libscotch/y.output
- setup/version.fh
they come from your local installation and should not be submitted. 

I'll add those also to .gitignore to avoid this in future. many thanks!

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by danielpeter** [comment]
i'm closing this pull request. please open a new PR as mentioned by buildbot to include your latest commit changes.

**Pull request closed without merging**
