### PR TITLE
added -o -name 'utils/ADJOINT_TOMOGRAPHY_TOOLS/flexwin' -prune to utils/clean_listings_specfem.pl

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 02/12/2015 12:00 AM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/404#issuecomment-73983917>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
Does this work? `-name` should only match the basename (no paths). I think it should be `-path ./utils/ADJOINT_TOMOGRAPHY_TOOLS/flexwin`.

**Comment by komatits** [comment]
Fixed!

On 02/12/2015 01:13 AM, Elliott Sales de Andrade wrote:
> Does this work? |-name| should only match the basename (no paths). I
> think it should be |-path ./utils/ADJOINT_TOMOGRAPHY_TOOLS/flexwin|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/404#issuecomment-73993244>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
