### PR TITLE
Add parallel fault support for kinematic rupture simulation.

### PR DESCRIPTION
**Pull request by kbai**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by luet** [comment]
Let me check what happened.

On Mon, Feb 29, 2016 at 8:44 PM, buildbot-princeton <
notifications@github.com> wrote:

> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/705#issuecomment-190486937>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 440](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/440). Fix your mistakes and push your changes back to your branch kbai/specfem3d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
It's a problem with unused variables:

    src/specfem3D/fault_solver_kinematic.f90:316.6:

      use specfem_par, only : NPROC,myrank
          1
    Warning: Unused module variable 'myrank' which has been explicitly imported at (1)
    src/specfem3D/fault_solver_kinematic.f90:316.6:
    
      use specfem_par, only : NPROC,myrank
      1
    Warning: Unused module variable 'nproc' which has been explicitly imported at (1)
    make: *** [obj/fault_solver_kinematic.spec.o] Error 1
    make: *** Waiting for unfinished jobs....

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 441](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/441).

**Comment by komatits** [comment]
accept

On 01/03/2016 19:25, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 441
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/441>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/705#issuecomment-190842019>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
