### PR TITLE
mostly performance updates, OpenMP for acoustics and PMLs; adds preparation for LTS 

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/decompose_mesh/partition_patoh.F90
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/decompose_mesh/partition_patoh.F90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/decompose_mesh/partition_patoh.F90-o src/decompose_mesh/partition_patoh.F90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 855](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/855).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
