### PR TITLE
Fix fault example tpv5 with a missing square bracket.

### PR DESCRIPTION
**Pull request by kbai**
Tested with cubit13.0.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 329](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/329).

**Comment by komatits** [comment]
accept

On 06/08/2015 01:16 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 329
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/329>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/544#issuecomment-109812956>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi Kangchen @kbai,

Still does not work, I still get:

CUBIT> #### DEFINE MATERIAL PROPERTIES #######################
CUBIT>
CUBIT> # Material properties in concordance with tpv5 benchmark.
CUBIT>
CUBIT> block 1 name "elastic 1"
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute count 5
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute index 1 1

(the end of the CUBIT text window looks OK but if you check the messages 
above you will see it).

Dimitri.

On 06/08/2015 01:09 AM, Kangchen Bai wrote:
> Tested with cubit13.0.
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/geodynamics/specfem3d/pull/544
>
>
>         Commit Summary
>
>   * Fix fault example tpv5 with a missing square bracket.
>
>
>         File Changes
>
>   * *M* EXAMPLES/fault_examples/tpv5/TPV5.py
>     <https://github.com/geodynamics/specfem3d/pull/544/files#diff-0> (6)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem3d/pull/544.patch
>   * https://github.com/geodynamics/specfem3d/pull/544.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/544>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
