### PR TITLE
CAVITY option

### PR DESCRIPTION
**Pull request by homnath**
I have added a CAVITY_FILE option to create a simple cavity in the builtin mesher. I also added a cavity/ example, and modified all Mesh_par_file s accordingly. Please check README file in cavity/ example for detail on the cavity option.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes cannot be merged with a fast-forward merge.
This indicates that your repo is out of sync with the central repo.
If you are using hub, do:
$ git pull
If your are not using hub, do:
$ git pull upstream devel
Then open a new pull-request.

**Comment by buildbot-princeton** [comment]
Your changes cannot be merged with a fast-forward merge.
This indicates that your repo is out of sync with the central repo.
If you are using hub, do:
$ git pull
If your are not using hub, do:
$ git pull upstream devel
Then open a new pull-request.

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 02/13/2016 04:52 AM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/699#issuecomment-183581136>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Dear David and Hom Nath,

Is this pull request OK? I accepted it, but never got the "Merged" email 
I usually get from BuildBot.

Thanks,
Dimitri.

On 02/13/2016 11:43 AM, Dimitri Komatitsch wrote:
> accept
>
> On 02/13/2016 04:52 AM, buildbot-princeton wrote:
>> The files changed do not require a buildbot test. The maintainers can
>> commit these changes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/pull/699#issuecomment-183581136>.
>>
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
It seems it was closed by BuildBot and thus never merged.

**Comment by luet** [comment]
This PR should not be merged because there are some conflicts.
@homnath It looks like you haven't done a git pull since January 15 ( commit: edcbb6b ) so your repo is behind. Just do that and you should open a new pull-request
@danielpeter your labelling "in progress" and removing the label confuses buildbot because it looks like you are reopening the pull-request that buildbot just closed. Would it be possible for this weekend to stop doing that? 
@komatits If buildbot closes a pull-request just ignore what happens next.

**Comment by homnath** [comment]
Dear all,

Let me check this. I thought I pulled just yesterday!

Best,
Hon Nath

**Comment by danielpeter** [comment]
hi David, 

for these "in progress" labels, it is probably a webhook from waffle.io which is doing this automatically. it probably helps to keep its display update to date, see:
https://waffle.io/geodynamics/specfem3d

i'll see if there are options to get rid of this automatic labeling. otherwise i'll delete the webhook again.
best,
daniel

**Comment by luet** [comment]
Hi Daniel,
I can probably modify the buildbot to not respond to this. I just don't
have time this weekend.
Best,
David

On Sat, Feb 13, 2016 at 8:09 AM, daniel peter <notifications@github.com>
wrote:

> hi David,
>
> for these "in progress" labels, it is probably a webhook from waffle.io
> which is doing this automatically. it probably helps to keep its display
> update to date, see:
> https://waffle.io/geodynamics/specfem3d
>
> i'll see if there are options to get rid of this automatic labeling.
> otherwise i'll delete the webhook again.
> best,
> daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/699#issuecomment-183662473>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
