### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by Huihuiweng**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 915](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/915).

**Comment by danielpeter** [comment]
thanks for resubmitting! will accept it shortly after the tests have passed...

for future PRs, please avoid all these explicit "Merge branch devel .." commits by using a `git rebase ..` command. for example, to rebase to the current devel branch of your upstream/devel version:
```
git fetch upstream
git rebase --interactive upstream/devel
```
otherwise, the commit history here will fill up quickly with all these Merge-commits.

**Comment by danielpeter** [comment]
yes, merging commits is also possible with the `git rebase --interactive ..` command. it will allow you in the edit dialog to squash a commit into a previous one by setting `s ..` in front of the commit instead of `pick ..`.

**Comment by danielpeter** [comment]
accept

On 18 Nov 2021, at 4:36 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 915<https://urldefense.com/v3/__http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/915__;!!Nmw4Hv0!nk3rB0Z_91YAKpSNcuYIGQiet8kixhFFs_iBX_dOswnIaN871gAIwtvVDvzKlhi3NoVC_w$>.

**Pull request merged**
