### PR TITLE
added xcombine_sem utility

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 243](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/243).

**Comment by rmodrak** [comment]
For the latest discussion, see issue 419:

 https://github.com/geodynamics/specfem3d/issues/419

**Comment by komatits** [comment]
accept

On 02/22/2015 04:48 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 243
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/243>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/431#issuecomment-75441384>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
