### PR TITLE
updates mpi routines and parallel.f90 file to be closer to global ver…

### PR DESCRIPTION
**Pull request by danielpeter**
…sion for future merge

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 344](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/344).

**Comment by danielpeter** [comment]
accept

**Comment by komatits** [comment]
accept

On 06/19/2015 04:24 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 344
> <http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/344>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/pull/569#issuecomment-113530357>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
